project_id = "zvvmahabgsjurfeygirg"

[functions.release-escrow]
verify_jwt = true

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = false

[functions.create-transfer-recipient]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.send-payout-notification]
verify_jwt = false

[functions.verify-bank-account]
verify_jwt = true

[functions.send-farmer-verification-email]
verify_jwt = false
